name: build and test feature branch
on:
  push:
    branches:
      - 'feature/**'
jobs:
    build-feature:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: pull and checkout from git repository
              run: |
                echo "Pulling latest changes from remote repository"
            
            - name: setup java 17
              uses: actions/setup-java@v4
              with:
                distribution: 'temurin'
                java-version: '17'
                    
            - name: build with gradle
              run: |
                mvn clean install
                echo "build with maven"