name: Publish jar as artifact
on:
    repository_dispatch:
        types: [ publish-artifact-event ]
jobs:
    download-artefact:
        runs-on: ubuntu-latest
        env:
            ARTIFACT_NAME: 'customer-0.0.1-SNAPSHOT.jar'
        permissions:
            contents: write
            pull-requests: write
        
        steps:
            - name: Debug Payload
              run: |
                echo ${{ github.event.client_payload.base_branch }}

            - uses: actions/checkout@v3
              with:
                ref: ${{ github.event.client_payload.base_branch }}
                fetch-depth: 0
            
            - name: check last hashid
              run: |
                git log -2
            
            - name: setup java 17
              uses: actions/setup-java@v4
              with:
                distribution: 'temurin'
                java-version: '17'

            - name: Cache local Maven repository
              uses: actions/cache@v3
              with:
                path: ~/.m2/repository
                key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                restore-keys: |
                    ${{ runner.os }}-maven-
            
            - name: build with maven
              run: |
                mvn clean test package -DskipTests=true --batch-mode --update-snapshots
                echo ls -R target/
                echo ls -la

            - name: Publish Package
              if: success()
              uses: actions/upload-artifact@v3
              with:
                name: quartz-jar
                path: ${{ github.workspace }}/target/${{ env.ARTIFACT_NAME }}